import turtle as t
b = t.Turtle()
wn = t.Screen()

wn=t.Screen()
t.Screen().bgcolor("black")
fontSetUp = ("Times New Roman",30,"normal")
fontSetUp2 = ("Times New Roman",80,"normal")
fontSetUP3 =  ("Times New Roman",0.5,"normal")


circle = t.Turtle(shape="circle")
circle.shapesize(8)
circle.color("blue")
start = t.Turtle()
start.speed(0)
start.color("green")
start.shape("square")
start.penup()
start.goto(-120,140)
directions = t.Turtle()
directions.speed(0)
directions.color("yellow")
directions.shape("square")
directions.penup()
directions.goto(-120,180)

# writer.fillcolor("red")
def writer1():
    writer = t.Turtle()
    writer.speed(0)
    writer.color("red")
    writer.penup()
    writer.goto(-200,210)
    writer.pendown()
    writer.write(" Connect 4! " , font=fontSetUp2)
    writer.penup()
    writer.goto(-300,-250)
    writer.pendown()
    writer.write("Created By: Charity Baylor and Taylor Blythe", font=fontSetUp)
    writer.penup()
    writer.goto(-110,160)
    writer.pendown()
    writer.write("Directions", font=fontSetUp)
    writer.penup()
    writer.goto(-110,120)
    writer.pendown()
    writer.write("Play", font=fontSetUp)
    writer.hideturtle()
def blueCircle():
    circle.penup()
    circle.goto(-10,-10)
    circle.pendown()
    circle.fillcolor("blue")
    circle.stamp()
    circle.penup()
    circle.goto(80,-10)
    circle.pendown()
    circle.fillcolor("red")
    circle.stamp()
def clearScreen():
    wn.clearscreen()
    t.Screen().bgcolor("black")


b.color("black")
b.speed(0)

def board():
  b.setheading(0)
  b.penup()
  b.goto(-300,300)
  b.pendown()
  b.color("blue")
  b.begin_fill()
  b.forward(700)
  b.setheading(270)
  b.forward(525)
  b.setheading(180)
  b.forward(700)
  b.setheading(90)
  b.forward(525)
  b.penup()
  b.end_fill()



#circles row 1
def row1():
  b.penup()
  b.goto(-210,250)
  b.pendown()
  b.color("white")
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(-115,250)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(-20,250)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.pendown()
  b.penup()
  b.goto(75,250)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(170,250)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(265,250)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(360,250)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()

#row 2
def row2():
  b.penup()
  b.goto(-210,170)
  b.pendown()
  b.color("white")
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(-115,170)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(-20,170)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(75,170)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(170,170)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(265,170)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(360,170)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()

def row3():
  b.penup()
  b.goto(-210,90)
  b.pendown()
  b.color("white")
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(-115,90)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(-20,90)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(75,90)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(170,90)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(265,90)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(360,90)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()


def row4():
  b.penup()
  b.goto(-210,10)
  b.pendown()
  b.color("white")
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(-115,10)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(-20,10)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(75,10)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(170,10)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(265,10)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(360,10)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()

def row5():
  b.penup()
  b.goto(-210,-80)
  b.pendown()
  b.color("white")
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(-115,-80)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(-20,-80)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(75,-80)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(170,-80)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(265,-80)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(360,-80)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()


def row6():
  b.penup()
  b.goto(-210,-160)
  b.pendown()
  b.color("white")
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(-115,-160)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(-20,-160)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(75,-160)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(170,-160)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(265,-160)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()
  b.penup()
  b.goto(360,-160)
  b.pendown()
  b.begin_fill()
  b.circle(30,360)
  b.end_fill()

def game(x,y):
  clearScreen()
  board()
  row1()
  row2()
  row3()
  row4()
  row5()
  row6()  
  main = t.Turtle()
  main.shape("square")
  main.color("green")
  main.penup()
  main.goto(-575,150)
  main.pendown() 
  writer = t.Turtle()
  writer.color("red")
  writer.penup()
  writer.goto(-560,130)
  writer.pendown()
  writer.write("Main Menu", font=fontSetUp)
  writer.hideturtle()
  main.onclick(mainMenu)
  play = t.Turtle()
  play.color("yellow")
  play.shape("square")
  play.penup()
  play.goto(-575,110)
  play.pendown()
  writer.penup()
  writer.goto(-560,90)
  writer.pendown()
  writer.write("Reset Game", font=fontSetUp)
  play.onclick(game)

def dScreen(x,y):
   clearScreen()
   directions.penup()
   directions.goto(-750,300)
   directions.pendown()
   directions.write("First player to connect four of their discs horizontally, vertically, or diagonally wins the game", font = fontSetUp)
   directions.penup()
   directions.goto(-325,200)
   directions.pendown()
   directions.color("blue")
   directions.write("Created by Charity Baylor and Taylor Blythe", font=fontSetUp)
   blueCircle()
   main = t.Turtle()
   main.color("yellow")
   main.shape("square")
   main.penup()
   main.goto(-150,-220)
   writes = t.Turtle()
   writes.penup()
   writes.goto(-140,-240)
   writes.pendown()
   writes.color("red")
   writes.write("Main Menu", font=fontSetUp)
  #  writes.penup()
  #  writes.goto(-150,-200)
  #  writes.pendown()
  #  writes.write("Play", font=fontSetUp)
  #  writes.hideturtle()
  #  main.write("Main M
  #  main.write("Main Menu", font=fontSetUp)
   main.onclick(mainMenu)
   start = t.Turtle()
   start.color("green")
   start.shape("square")
   start.penup()
   start.goto(-150,-160)
   start.pendown()
   writes.penup()
   writes.goto(-140,-180)
   writes.pendown()
   writes.write("Play", font=fontSetUp)
   writes.hideturtle()
   start.onclick(game)
  



def mainMenu(x,y): 
   clearScreen()
   writer1()
   blueCircle()
   start = t.Turtle()
   start.color("green")
   start.shape("square")
   start.penup()
   start.goto(-120,140)
   start.onclick(game)
   directions = t.Turtle()
   directions.color("yellow")
   directions.shape("square")
   directions.penup()
   directions.goto(-120,180)
   directions.onclick(dScreen)

def winner():
  winner = t.Turtle()
  winner.color("red")
  winner.penup()
  winner.goto(-200,400)
  winner.pendown()
  winner.write("Winner")
   
writer1()
blueCircle()
start.onclick(game)
directions.onclick(dScreen)


# directions.onclick(directionsScreen)
wn.onkeypress(writer1,"q")
wn.listen()


wn.mainloop()